### ISSUE TITLE
Not working on iOS device (iPad)

### ISSUE THREAD

**Issue by jsuske1985** [microsoftgraph/msgraph-training-xamarin#12]
Hello, I followed the tutorial step by step and everything works on simulator, but not a device...this line of code just hangs there which attempting to login....what am I doing wrong? I have been struggling with for days now.

`var authResult = await interactiveRequest.ExecuteAsync();`

PLEASE HELP!

**Comment by jasonjoh** [comment]
@jsuske1985 this might be an issue with entitlements. I've found a lot of times things will work on the simulator, but in order to work on a physical device, your developer cert has to have all the right settings, etc.

Running this tutorial on a physical device is a bit outside the intended scope, but I'm scheduled to do an update pass on this tutorial to update MSAL and Graph SDK to the latest versions. While I'm doing that, I'll try to figure out what additional steps are needed to run on a physical iOS device.

**Comment by jsuske1985** [comment]
Turns out I was not login to iCloud on my device, therefore iCloud Keychain was not login.

**Comment by jasonjoh** [comment]
Ah ok :). There's a whole lot of iOS specifics over on the MSAL GitHub: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-iOS-specifics
